package loop:core@0.1.0;

world core {
  type log-level = enum {
    trace,
    debug,
    info,
    warn,
    error,
    fatal,
  }

  type cancel-token = u64

  export cancel: interface {
    new-token: func() -> cancel-token
    cancel: func(token: cancel-token)
    is-cancelled: func(token: cancel-token) -> bool
  }
}
