// Dock currently ships the Graphite runtime-backed model and geometry helpers
// that power the UI workbench. The abandoned graphite-core experiment was
// removed so this package exposes a single coherent surface again.
export {
    createDockInteractionController,
    computeDropIndicator,
    computeLayoutRects,
    type DockAddPanelIntentPayload,
    createDockIntentNames,
    createDockPanelQuery,
    createDockState,
    deserializeDockState,
    createGroupNode,
    normalizeDockState,
    createPanelNode,
    createSplitNode,
    registerDockIntents,
    removeDockStateAtPath,
    serializeDockState,
    splitDirectionFromZone,
    type DockDropIndicator,
    type DockDropIndicatorOptions,
    type DockDropTarget,
    type DockGroupNode,
    type DockGroupLayout,
    type DockHitTestOptions,
    type DockInteractionController,
    type DockInteractionIntent,
    type DockLayoutMap,
    type DockLayoutNodeLayout,
    type DockLayoutOptions,
    type DockMovePanelIntentPayload,
    type DockNode,
    type DockNodeId,
    type DockPanelNode,
    type DockPanelSummary,
    type Point,
    type DockResizeIntentPayload,
    type DockResizeSessionStart,
    type Rect,
    type DockSplitHandleLayout,
    type DockState,
} from './graphite/index.js';
export type {
    DockSplitDirection as GraphiteDockSplitDirection,
    Rect as GraphiteDockRect,
} from './graphite/index.js';
