import { defaultDarkTheme, defaultLightTheme } from '../theme/default-themes';
import { ThemeSchema, type ThemeDefinition } from '../theme/schema';
import { defaultDarkTokens, defaultLightTokens, type Tokens } from '../tokens';
import { createUiSkinRegistry } from './registry';
import type { ResolvedUiSkin, UiSkinDefinition } from './schema';

function cloneTheme(theme: ThemeDefinition): ThemeDefinition {
    return structuredClone(theme);
}

function patchTokens(base: Tokens, patch: Partial<Tokens>): Tokens {
    return {
        ...base,
        ...patch,
        colors: {
            ...base.colors,
            ...(patch.colors ?? {}),
        },
        radius: {
            ...base.radius,
            ...(patch.radius ?? {}),
        },
        spacing: {
            ...base.spacing,
            ...(patch.spacing ?? {}),
        },
        typography: {
            ...base.typography,
            ...(patch.typography ?? {}),
        },
        elevation: {
            ...base.elevation,
            ...(patch.elevation ?? {}),
        },
        fx: {
            ...base.fx,
            ...(patch.fx ?? {}),
        },
    };
}

function createThemeDefinition(
    id: string,
    mode: 'light' | 'dark',
    baseTheme: ThemeDefinition,
    tokenPatch: Partial<Tokens>,
): ThemeDefinition {
    return ThemeSchema.parse({
        ...cloneTheme(baseTheme),
        id,
        mode,
        tokens: patchTokens(baseTheme.tokens, tokenPatch),
    });
}

export const DEFAULT_UI_SKIN_ID = 'forge';

export const defaultUiSkinDefinitions: Record<string, UiSkinDefinition> = {
    classic: {
        id: 'classic',
        label: 'Classic',
        description: 'Baseline Loop tokens.',
        source: '@loop-kit/ui/theme/defaultThemeSet',
        tags: ['default', 'stable'],
        themes: {
            light: {
                id: 'classic-light',
                mode: 'light',
                tokens: defaultLightTokens,
            },
            dark: {
                id: 'classic-dark',
                mode: 'dark',
                tokens: defaultDarkTokens,
            },
        },
    },
    graphite: {
        id: 'graphite',
        label: 'Graphite',
        description: 'High-contrast productivity skin tuned for dense workspaces.',
        extends: 'classic',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['graphite', 'dock', 'dense'],
        themes: {
            light: createThemeDefinition('graphite-light', 'light', defaultLightTheme, {
                colors: {
                    background: 'oklch(0.97 0.01 260)',
                    foreground: 'oklch(0.28 0.03 260)',
                    surface: 'oklch(0.99 0.005 260)',
                    surfaceForeground: 'oklch(0.28 0.03 260)',
                    border: 'oklch(0.86 0.01 260)',
                    accent: 'oklch(0.58 0.15 230)',
                    accentForeground: 'oklch(0.99 0.01 235)',
                    muted: 'oklch(0.93 0.01 260)',
                    mutedForeground: 'oklch(0.46 0.03 260)',
                    danger: 'oklch(0.62 0.2 28)',
                    dangerForeground: 'oklch(0.98 0.01 28)',
                },
                radius: {
                    sm: '0.2rem',
                    md: '0.35rem',
                    lg: '0.55rem',
                    xl: '0.9rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"IBM Plex Sans", "Inter", sans-serif',
                    familyMono: '"JetBrains Mono", "Fira Code", monospace',
                    sizeSm: '0.75rem',
                    sizeMd: '0.875rem',
                    sizeLg: '1rem',
                    weightNormal: '410',
                    weightMedium: '560',
                    weightBold: '680',
                    lineHeight: '1.5',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-01',
                    panelOverlayOpacity: '0.22',
                    glassBlur: '10px',
                },
            }),
            dark: createThemeDefinition('graphite-dark', 'dark', defaultDarkTheme, {
                colors: {
                    background: 'oklch(0.17 0.01 250)',
                    foreground: 'oklch(0.9 0.015 250)',
                    surface: 'oklch(0.22 0.012 250)',
                    surfaceForeground: 'oklch(0.93 0.02 250)',
                    border: 'oklch(0.33 0.01 250)',
                    accent: 'oklch(0.74 0.14 225)',
                    accentForeground: 'oklch(0.2 0.02 230)',
                    muted: 'oklch(0.26 0.01 250)',
                    mutedForeground: 'oklch(0.7 0.02 250)',
                    danger: 'oklch(0.66 0.2 28)',
                    dangerForeground: 'oklch(0.2 0.02 28)',
                },
                radius: {
                    sm: '0.2rem',
                    md: '0.35rem',
                    lg: '0.55rem',
                    xl: '0.9rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"IBM Plex Sans", "Inter", sans-serif',
                    familyMono: '"JetBrains Mono", "Fira Code", monospace',
                    sizeSm: '0.75rem',
                    sizeMd: '0.875rem',
                    sizeLg: '1rem',
                    weightNormal: '410',
                    weightMedium: '560',
                    weightBold: '680',
                    lineHeight: '1.5',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-02',
                    panelOverlayOpacity: '0.28',
                    glassBlur: '12px',
                },
            }),
        },
    },
    sunset: {
        id: 'sunset',
        label: 'Sunset',
        description: 'Warm rounded reskin with stronger depth and motion contrast.',
        extends: 'classic',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['warm', 'reskin'],
        themes: {
            light: createThemeDefinition('sunset-light', 'light', defaultLightTheme, {
                colors: {
                    background: 'oklch(0.97 0.03 75)',
                    foreground: 'oklch(0.34 0.06 42)',
                    surface: 'oklch(0.99 0.02 88)',
                    surfaceForeground: 'oklch(0.36 0.06 44)',
                    border: 'oklch(0.86 0.06 70)',
                    accent: 'oklch(0.69 0.2 34)',
                    accentForeground: 'oklch(0.98 0.01 85)',
                    muted: 'oklch(0.92 0.03 70)',
                    mutedForeground: 'oklch(0.5 0.08 40)',
                    danger: 'oklch(0.62 0.24 26)',
                    dangerForeground: 'oklch(0.98 0.01 26)',
                },
                radius: {
                    sm: '0.35rem',
                    md: '0.65rem',
                    lg: '1rem',
                    xl: '1.4rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Sora", "Avenir Next", sans-serif',
                    familyMono: '"IBM Plex Mono", monospace',
                    sizeSm: '0.76rem',
                    sizeMd: '0.92rem',
                    sizeLg: '1.08rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.45',
                },
                elevation: {
                    level1: '0 3px 12px oklch(0.55 0.07 45 / 0.14)',
                    level2: '0 8px 24px oklch(0.45 0.09 35 / 0.18)',
                    level3: '0 14px 42px oklch(0.4 0.11 30 / 0.24)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/mesh-01',
                    panelOverlayOpacity: '0.2',
                    glassBlur: '6px',
                },
            }),
            dark: createThemeDefinition('sunset-dark', 'dark', defaultDarkTheme, {
                colors: {
                    background: 'oklch(0.2 0.03 18)',
                    foreground: 'oklch(0.92 0.03 80)',
                    surface: 'oklch(0.24 0.03 20)',
                    surfaceForeground: 'oklch(0.93 0.03 78)',
                    border: 'oklch(0.38 0.04 26)',
                    accent: 'oklch(0.75 0.2 42)',
                    accentForeground: 'oklch(0.24 0.03 22)',
                    muted: 'oklch(0.28 0.03 22)',
                    mutedForeground: 'oklch(0.72 0.04 66)',
                    danger: 'oklch(0.68 0.22 28)',
                    dangerForeground: 'oklch(0.24 0.03 26)',
                },
                radius: {
                    sm: '0.35rem',
                    md: '0.65rem',
                    lg: '1rem',
                    xl: '1.4rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Sora", "Avenir Next", sans-serif',
                    familyMono: '"IBM Plex Mono", monospace',
                    sizeSm: '0.76rem',
                    sizeMd: '0.92rem',
                    sizeLg: '1.08rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.45',
                },
                elevation: {
                    level1: '0 2px 8px oklch(0.1 0.02 24 / 0.4)',
                    level2: '0 8px 22px oklch(0.08 0.02 22 / 0.5)',
                    level3: '0 14px 36px oklch(0.06 0.02 20 / 0.56)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-03',
                    panelOverlayOpacity: '0.34',
                    glassBlur: '12px',
                },
            }),
        },
    },
    forge: {
        id: 'forge',
        label: 'Forge',
        description: 'Steel-blue operator skin tuned for dense multi-panel work.',
        extends: 'graphite',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['forge', 'operator', 'dense'],
        themes: {
            light: createThemeDefinition('forge-light', 'light', defaultLightTheme, {
                colors: {
                    background: 'oklch(0.97 0.008 240)',
                    foreground: 'oklch(0.24 0.03 248)',
                    surface: 'oklch(0.995 0.004 245)',
                    surfaceForeground: 'oklch(0.24 0.03 248)',
                    border: 'oklch(0.86 0.012 245)',
                    accent: 'oklch(0.57 0.16 235)',
                    accentForeground: 'oklch(0.985 0.01 245)',
                    muted: 'oklch(0.93 0.008 245)',
                    mutedForeground: 'oklch(0.47 0.025 245)',
                    danger: 'oklch(0.63 0.19 30)',
                    dangerForeground: 'oklch(0.99 0.01 30)',
                },
                typography: {
                    familySans: '"Aptos", "IBM Plex Sans", sans-serif',
                    familyMono: '"JetBrains Mono", "Cascadia Code", monospace',
                    sizeSm: '0.78rem',
                    sizeMd: '0.9rem',
                    sizeLg: '1.04rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.48',
                },
                elevation: {
                    level1: '0 8px 18px oklch(0.58 0.03 245 / 0.14)',
                    level2: '0 16px 32px oklch(0.52 0.04 245 / 0.2)',
                    level3: '0 24px 56px oklch(0.48 0.05 245 / 0.28)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/mesh-01',
                    panelOverlayOpacity: '0.16',
                    glassBlur: '18px',
                },
            }),
            dark: createThemeDefinition('forge-dark', 'dark', defaultDarkTheme, {
                colors: {
                    background: 'oklch(0.15 0.012 245)',
                    foreground: 'oklch(0.93 0.015 250)',
                    surface: 'oklch(0.19 0.013 245)',
                    surfaceForeground: 'oklch(0.94 0.015 250)',
                    border: 'oklch(0.32 0.015 245)',
                    accent: 'oklch(0.72 0.15 235)',
                    accentForeground: 'oklch(0.18 0.015 245)',
                    muted: 'oklch(0.24 0.012 245)',
                    mutedForeground: 'oklch(0.73 0.02 245)',
                    danger: 'oklch(0.67 0.19 30)',
                    dangerForeground: 'oklch(0.18 0.015 245)',
                },
                typography: {
                    familySans: '"Aptos", "IBM Plex Sans", sans-serif',
                    familyMono: '"JetBrains Mono", "Cascadia Code", monospace',
                    sizeSm: '0.78rem',
                    sizeMd: '0.9rem',
                    sizeLg: '1.04rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.48',
                },
                elevation: {
                    level1: '0 10px 24px oklch(0.02 0.01 245 / 0.35)',
                    level2: '0 20px 44px oklch(0.02 0.01 245 / 0.44)',
                    level3: '0 28px 68px oklch(0.02 0.01 245 / 0.56)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-03',
                    panelOverlayOpacity: '0.22',
                    glassBlur: '18px',
                },
            }),
        },
        iconAliases: {
            search: 'wrench',
            menu: 'settings2',
        },
        metadata: {
            accentIntent: 'operator',
        },
    },
    atelier: {
        id: 'atelier',
        label: 'Atelier',
        description: 'Pearlescent editorial skin with softer contrast and richer atmosphere.',
        extends: 'classic',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['editorial', 'glamour', 'demo'],
        themes: {
            light: createThemeDefinition('atelier-light', 'light', defaultLightTheme, {
                colors: {
                    background: 'oklch(0.978 0.012 82)',
                    foreground: 'oklch(0.27 0.028 255)',
                    surface: 'oklch(0.993 0.008 90)',
                    surfaceForeground: 'oklch(0.27 0.028 255)',
                    border: 'oklch(0.88 0.02 88)',
                    accent: 'oklch(0.73 0.16 28)',
                    accentForeground: 'oklch(0.985 0.008 92)',
                    muted: 'oklch(0.94 0.015 84)',
                    mutedForeground: 'oklch(0.46 0.03 255)',
                    danger: 'oklch(0.65 0.19 24)',
                    dangerForeground: 'oklch(0.99 0.01 24)',
                },
                radius: {
                    sm: '0.45rem',
                    md: '0.8rem',
                    lg: '1.25rem',
                    xl: '1.75rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Space Grotesk", "Aptos", sans-serif',
                    familyMono: '"IBM Plex Mono", "JetBrains Mono", monospace',
                    sizeSm: '0.79rem',
                    sizeMd: '0.95rem',
                    sizeLg: '1.12rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.5',
                },
                elevation: {
                    level1: '0 8px 22px oklch(0.72 0.05 70 / 0.12)',
                    level2: '0 18px 44px oklch(0.56 0.05 38 / 0.18)',
                    level3: '0 28px 70px oklch(0.45 0.04 28 / 0.24)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/mesh-01',
                    panelOverlayOpacity: '0.1',
                    glassBlur: '22px',
                },
            }),
            dark: createThemeDefinition('atelier-dark', 'dark', defaultDarkTheme, {
                colors: {
                    background: 'oklch(0.2 0.018 252)',
                    foreground: 'oklch(0.94 0.018 90)',
                    surface: 'oklch(0.24 0.018 250)',
                    surfaceForeground: 'oklch(0.95 0.018 90)',
                    border: 'oklch(0.35 0.02 248)',
                    accent: 'oklch(0.78 0.14 30)',
                    accentForeground: 'oklch(0.22 0.018 252)',
                    muted: 'oklch(0.28 0.018 248)',
                    mutedForeground: 'oklch(0.76 0.025 92)',
                    danger: 'oklch(0.69 0.2 24)',
                    dangerForeground: 'oklch(0.21 0.018 252)',
                },
                radius: {
                    sm: '0.45rem',
                    md: '0.8rem',
                    lg: '1.25rem',
                    xl: '1.75rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Space Grotesk", "Aptos", sans-serif',
                    familyMono: '"IBM Plex Mono", "JetBrains Mono", monospace',
                    sizeSm: '0.79rem',
                    sizeMd: '0.95rem',
                    sizeLg: '1.12rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.5',
                },
                elevation: {
                    level1: '0 10px 24px oklch(0.04 0.01 250 / 0.32)',
                    level2: '0 22px 48px oklch(0.04 0.01 250 / 0.42)',
                    level3: '0 34px 82px oklch(0.04 0.01 250 / 0.52)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-02',
                    panelOverlayOpacity: '0.16',
                    glassBlur: '24px',
                },
            }),
        },
        metadata: {
            accentIntent: 'editorial',
        },
    },
    'textured-panels': {
        id: 'textured-panels',
        label: 'Textured Panels',
        description: 'Textured editorial surfaces with warmer contrast and ornamental framing.',
        extends: 'atelier',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['texture', 'ornament', '9-slice'],
        themes: {
            light: createThemeDefinition('textured-panels-light', 'light', defaultLightTheme, {
                colors: {
                    background: 'oklch(0.975 0.018 86)',
                    foreground: 'oklch(0.28 0.03 42)',
                    surface: 'oklch(0.992 0.01 92)',
                    surfaceForeground: 'oklch(0.28 0.03 42)',
                    border: 'oklch(0.84 0.06 70)',
                    accent: 'oklch(0.67 0.18 45)',
                    accentForeground: 'oklch(0.99 0.01 85)',
                    muted: 'oklch(0.93 0.02 82)',
                    mutedForeground: 'oklch(0.48 0.05 40)',
                    danger: 'oklch(0.64 0.22 26)',
                    dangerForeground: 'oklch(0.99 0.01 85)',
                },
                typography: {
                    familySans: '"Fraunces", "Aptos Display", serif',
                    familyMono: '"IBM Plex Mono", monospace',
                    sizeSm: '0.8rem',
                    sizeMd: '0.98rem',
                    sizeLg: '1.14rem',
                    weightNormal: '430',
                    weightMedium: '620',
                    weightBold: '740',
                    lineHeight: '1.58',
                },
                elevation: {
                    level1: '0 10px 26px oklch(0.6 0.08 40 / 0.12)',
                    level2: '0 20px 48px oklch(0.48 0.08 35 / 0.18)',
                    level3: '0 34px 80px oklch(0.4 0.08 28 / 0.24)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/mesh-01',
                    panelOverlayOpacity: '0.18',
                    glassBlur: '10px',
                },
            }),
            dark: createThemeDefinition('textured-panels-dark', 'dark', defaultDarkTheme, {
                colors: {
                    background: 'oklch(0.19 0.02 34)',
                    foreground: 'oklch(0.94 0.018 92)',
                    surface: 'oklch(0.23 0.02 34)',
                    surfaceForeground: 'oklch(0.95 0.018 92)',
                    border: 'oklch(0.36 0.05 46)',
                    accent: 'oklch(0.76 0.16 45)',
                    accentForeground: 'oklch(0.22 0.02 34)',
                    muted: 'oklch(0.27 0.02 34)',
                    mutedForeground: 'oklch(0.74 0.03 84)',
                    danger: 'oklch(0.68 0.2 24)',
                    dangerForeground: 'oklch(0.22 0.02 34)',
                },
                typography: {
                    familySans: '"Fraunces", "Aptos Display", serif',
                    familyMono: '"IBM Plex Mono", monospace',
                    sizeSm: '0.8rem',
                    sizeMd: '0.98rem',
                    sizeLg: '1.14rem',
                    weightNormal: '430',
                    weightMedium: '620',
                    weightBold: '740',
                    lineHeight: '1.58',
                },
                elevation: {
                    level1: '0 14px 26px oklch(0.04 0.01 30 / 0.36)',
                    level2: '0 24px 58px oklch(0.03 0.01 30 / 0.44)',
                    level3: '0 38px 92px oklch(0.02 0.01 30 / 0.52)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-03',
                    panelOverlayOpacity: '0.22',
                    glassBlur: '12px',
                },
            }),
        },
    },
    'liquid-glass': {
        id: 'liquid-glass',
        label: 'Liquid Glass',
        description: 'Glassier surfaces with luminous gradients and softer chrome.',
        extends: 'forge',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['glass', 'luminous'],
        themes: {
            light: createThemeDefinition('liquid-glass-light', 'light', defaultLightTheme, {
                colors: {
                    background: 'oklch(0.96 0.02 235)',
                    foreground: 'oklch(0.23 0.03 252)',
                    surface: 'oklch(0.99 0.008 240 / 0.78)',
                    surfaceForeground: 'oklch(0.23 0.03 252)',
                    border: 'oklch(0.9 0.012 240 / 0.72)',
                    accent: 'oklch(0.68 0.17 215)',
                    accentForeground: 'oklch(0.99 0.008 240)',
                    muted: 'oklch(0.93 0.012 240 / 0.78)',
                    mutedForeground: 'oklch(0.44 0.03 245)',
                    danger: 'oklch(0.65 0.2 28)',
                    dangerForeground: 'oklch(0.99 0.008 240)',
                },
                radius: {
                    sm: '0.7rem',
                    md: '0.95rem',
                    lg: '1.4rem',
                    xl: '1.9rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Manrope", "Aptos", sans-serif',
                    familyMono: '"JetBrains Mono", monospace',
                    sizeSm: '0.78rem',
                    sizeMd: '0.94rem',
                    sizeLg: '1.12rem',
                    weightNormal: '430',
                    weightMedium: '620',
                    weightBold: '730',
                    lineHeight: '1.46',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-01',
                    panelOverlayOpacity: '0.08',
                    glassBlur: '26px',
                },
            }),
            dark: createThemeDefinition('liquid-glass-dark', 'dark', defaultDarkTheme, {
                colors: {
                    background: 'oklch(0.16 0.016 244)',
                    foreground: 'oklch(0.94 0.015 245)',
                    surface: 'oklch(0.22 0.012 242 / 0.72)',
                    surfaceForeground: 'oklch(0.95 0.016 245)',
                    border: 'oklch(0.44 0.02 240 / 0.46)',
                    accent: 'oklch(0.78 0.14 225)',
                    accentForeground: 'oklch(0.19 0.014 242)',
                    muted: 'oklch(0.27 0.01 242 / 0.72)',
                    mutedForeground: 'oklch(0.72 0.02 242)',
                    danger: 'oklch(0.68 0.19 28)',
                    dangerForeground: 'oklch(0.19 0.014 242)',
                },
                radius: {
                    sm: '0.7rem',
                    md: '0.95rem',
                    lg: '1.4rem',
                    xl: '1.9rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Manrope", "Aptos", sans-serif',
                    familyMono: '"JetBrains Mono", monospace',
                    sizeSm: '0.78rem',
                    sizeMd: '0.94rem',
                    sizeLg: '1.12rem',
                    weightNormal: '430',
                    weightMedium: '620',
                    weightBold: '730',
                    lineHeight: '1.46',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-02',
                    panelOverlayOpacity: '0.12',
                    glassBlur: '28px',
                },
            }),
        },
    },
    'neo-brutal': {
        id: 'neo-brutal',
        label: 'Neo Brutal',
        description: 'Sharp, loud, and contrast-heavy with hard edges and playful depth.',
        extends: 'classic',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['neobrutalism', 'contrast'],
        themes: {
            light: createThemeDefinition('neo-brutal-light', 'light', defaultLightTheme, {
                colors: {
                    background: 'oklch(0.96 0.03 96)',
                    foreground: 'oklch(0.2 0.02 260)',
                    surface: 'oklch(0.99 0.01 96)',
                    surfaceForeground: 'oklch(0.2 0.02 260)',
                    border: 'oklch(0.2 0.02 260)',
                    accent: 'oklch(0.74 0.21 24)',
                    accentForeground: 'oklch(0.98 0.01 96)',
                    muted: 'oklch(0.9 0.03 96)',
                    mutedForeground: 'oklch(0.34 0.05 250)',
                    danger: 'oklch(0.7 0.22 28)',
                    dangerForeground: 'oklch(0.98 0.01 96)',
                },
                radius: {
                    sm: '0.3rem',
                    md: '0.4rem',
                    lg: '0.55rem',
                    xl: '0.8rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Archivo", "IBM Plex Sans", sans-serif',
                    familyMono: '"IBM Plex Mono", monospace',
                    sizeSm: '0.8rem',
                    sizeMd: '0.96rem',
                    sizeLg: '1.15rem',
                    weightNormal: '520',
                    weightMedium: '700',
                    weightBold: '820',
                    lineHeight: '1.38',
                },
                elevation: {
                    level1: '4px 4px 0 oklch(0.2 0.02 260)',
                    level2: '8px 8px 0 oklch(0.2 0.02 260)',
                    level3: '12px 12px 0 oklch(0.2 0.02 260)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-01',
                    panelOverlayOpacity: '0.06',
                    glassBlur: '0px',
                },
            }),
            dark: createThemeDefinition('neo-brutal-dark', 'dark', defaultDarkTheme, {
                colors: {
                    background: 'oklch(0.19 0.02 255)',
                    foreground: 'oklch(0.97 0.01 92)',
                    surface: 'oklch(0.24 0.02 255)',
                    surfaceForeground: 'oklch(0.97 0.01 92)',
                    border: 'oklch(0.97 0.01 92)',
                    accent: 'oklch(0.78 0.19 32)',
                    accentForeground: 'oklch(0.2 0.02 255)',
                    muted: 'oklch(0.32 0.02 255)',
                    mutedForeground: 'oklch(0.82 0.02 92)',
                    danger: 'oklch(0.74 0.2 28)',
                    dangerForeground: 'oklch(0.2 0.02 255)',
                },
                radius: {
                    sm: '0.3rem',
                    md: '0.4rem',
                    lg: '0.55rem',
                    xl: '0.8rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Archivo", "IBM Plex Sans", sans-serif',
                    familyMono: '"IBM Plex Mono", monospace',
                    sizeSm: '0.8rem',
                    sizeMd: '0.96rem',
                    sizeLg: '1.15rem',
                    weightNormal: '520',
                    weightMedium: '700',
                    weightBold: '820',
                    lineHeight: '1.38',
                },
                elevation: {
                    level1: '4px 4px 0 oklch(0.97 0.01 92)',
                    level2: '8px 8px 0 oklch(0.97 0.01 92)',
                    level3: '12px 12px 0 oklch(0.97 0.01 92)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-02',
                    panelOverlayOpacity: '0.08',
                    glassBlur: '0px',
                },
            }),
        },
    },
    'slate-glow': {
        id: 'slate-glow',
        label: 'Slate Glow',
        description: 'Shadowy slate surfaces with muted glow for Forge operator views.',
        extends: 'forge',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['slate', 'glow', 'operator'],
        themes: {
            light: createThemeDefinition('slate-glow-light', 'light', defaultLightTheme, {
                colors: {
                    background: 'oklch(0.95 0.006 250)',
                    foreground: 'oklch(0.24 0.02 252)',
                    surface: 'oklch(0.985 0.005 250)',
                    surfaceForeground: 'oklch(0.24 0.02 252)',
                    border: 'oklch(0.84 0.01 248)',
                    accent: 'oklch(0.64 0.14 235)',
                    accentForeground: 'oklch(0.985 0.008 250)',
                    muted: 'oklch(0.92 0.006 248)',
                    mutedForeground: 'oklch(0.46 0.02 248)',
                    danger: 'oklch(0.64 0.2 28)',
                    dangerForeground: 'oklch(0.985 0.008 250)',
                },
                typography: {
                    familySans: '"Geist Sans", "Aptos", sans-serif',
                    familyMono: '"Geist Mono", "JetBrains Mono", monospace',
                    sizeSm: '0.78rem',
                    sizeMd: '0.92rem',
                    sizeLg: '1.08rem',
                    weightNormal: '430',
                    weightMedium: '590',
                    weightBold: '710',
                    lineHeight: '1.48',
                },
                elevation: {
                    level1: '0 10px 24px oklch(0.5 0.02 250 / 0.14)',
                    level2: '0 18px 44px oklch(0.42 0.02 250 / 0.2)',
                    level3: '0 28px 68px oklch(0.38 0.03 250 / 0.28)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-01',
                    panelOverlayOpacity: '0.1',
                    glassBlur: '18px',
                },
            }),
            dark: createThemeDefinition('slate-glow-dark', 'dark', defaultDarkTheme, {
                colors: {
                    background: 'oklch(0.14 0.008 252)',
                    foreground: 'oklch(0.93 0.012 250)',
                    surface: 'oklch(0.18 0.008 250)',
                    surfaceForeground: 'oklch(0.94 0.014 250)',
                    border: 'oklch(0.3 0.01 250)',
                    accent: 'oklch(0.7 0.14 232)',
                    accentForeground: 'oklch(0.18 0.01 250)',
                    muted: 'oklch(0.22 0.008 250)',
                    mutedForeground: 'oklch(0.72 0.015 250)',
                    danger: 'oklch(0.68 0.19 28)',
                    dangerForeground: 'oklch(0.18 0.01 250)',
                },
                typography: {
                    familySans: '"Geist Sans", "Aptos", sans-serif',
                    familyMono: '"Geist Mono", "JetBrains Mono", monospace',
                    sizeSm: '0.78rem',
                    sizeMd: '0.92rem',
                    sizeLg: '1.08rem',
                    weightNormal: '430',
                    weightMedium: '590',
                    weightBold: '710',
                    lineHeight: '1.48',
                },
                elevation: {
                    level1: '0 12px 26px oklch(0.02 0.01 250 / 0.36)',
                    level2: '0 22px 52px oklch(0.02 0.01 250 / 0.46)',
                    level3: '0 34px 86px oklch(0.02 0.01 250 / 0.58)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-03',
                    panelOverlayOpacity: '0.14',
                    glassBlur: '18px',
                },
            }),
        },
    },
};

export const defaultUiSkinRegistry = createUiSkinRegistry({
    skins: defaultUiSkinDefinitions,
});

export const defaultUiSkins = defaultUiSkinRegistry.resolved();

export const defaultUiSkin = defaultUiSkins[DEFAULT_UI_SKIN_ID]!;

export function resolveDefaultUiSkin(id: string = DEFAULT_UI_SKIN_ID): ResolvedUiSkin {
    return defaultUiSkins[id] ?? defaultUiSkin;
}
