import { defaultDarkTheme, defaultLightTheme } from '../theme/default-themes';
import { ThemeSchema, type ThemeDefinition } from '../theme/schema';
import {
    createSemanticColors,
    defaultDarkTokens,
    defaultLightTokens,
    type Tokens,
} from '../tokens';
import { createUiSkinRegistry } from './registry';
import type { ResolvedUiSkin, UiSkinDefinition } from './schema';

function cloneTheme(theme: ThemeDefinition): ThemeDefinition {
    return structuredClone(theme);
}

function patchTokens(base: Tokens, patch: Partial<Tokens>): Tokens {
    return {
        ...base,
        ...patch,
        colors: {
            ...base.colors,
            ...(patch.colors ?? {}),
        },
        radius: {
            ...base.radius,
            ...(patch.radius ?? {}),
        },
        spacing: {
            ...base.spacing,
            ...(patch.spacing ?? {}),
        },
        typography: {
            ...base.typography,
            ...(patch.typography ?? {}),
        },
        elevation: {
            ...base.elevation,
            ...(patch.elevation ?? {}),
        },
        fx: {
            ...base.fx,
            ...(patch.fx ?? {}),
        },
    };
}

function createThemeDefinition(
    id: string,
    mode: 'light' | 'dark',
    baseTheme: ThemeDefinition,
    tokenPatch: Partial<Tokens>,
): ThemeDefinition {
    return ThemeSchema.parse({
        ...cloneTheme(baseTheme),
        id,
        mode,
        tokens: patchTokens(baseTheme.tokens, tokenPatch),
    });
}

export const DEFAULT_UI_SKIN_ID = 'forge';

export const defaultUiSkinDefinitions: Record<string, UiSkinDefinition> = {
    classic: {
        id: 'classic',
        label: 'Classic',
        description: 'Baseline Loop tokens.',
        source: '@loop-kit/ui/theme/defaultThemeSet',
        tags: ['default', 'stable'],
        themes: {
            light: {
                id: 'classic-light',
                mode: 'light',
                tokens: defaultLightTokens,
            },
            dark: {
                id: 'classic-dark',
                mode: 'dark',
                tokens: defaultDarkTokens,
            },
        },
    },
    graphite: {
        id: 'graphite',
        label: 'Graphite',
        description: 'High-contrast productivity skin tuned for dense workspaces.',
        extends: 'classic',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['graphite', 'dock', 'dense'],
        themes: {
            light: createThemeDefinition('graphite-light', 'light', defaultLightTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.97 0.01 260)',
                    foreground: 'oklch(0.28 0.03 260)',
                    card: 'oklch(0.99 0.005 260)',
                    cardForeground: 'oklch(0.28 0.03 260)',
                    border: 'oklch(0.86 0.01 260)',
                    primary: 'oklch(0.58 0.15 230)',
                    primaryForeground: 'oklch(0.99 0.01 235)',
                    secondary: 'oklch(0.945 0.01 260)',
                    secondaryForeground: 'oklch(0.3 0.03 260)',
                    muted: 'oklch(0.93 0.01 260)',
                    mutedForeground: 'oklch(0.46 0.03 260)',
                    accent: 'oklch(0.9 0.016 255)',
                    accentForeground: 'oklch(0.28 0.03 260)',
                    destructive: 'oklch(0.62 0.2 28)',
                    destructiveForeground: 'oklch(0.98 0.01 28)',
                    sidebar: 'oklch(0.955 0.008 258)',
                    sidebarForeground: 'oklch(0.26 0.03 260)',
                    sidebarAccent: 'oklch(0.9 0.014 252)',
                    sidebarAccentForeground: 'oklch(0.26 0.03 260)',
                    sidebarBorder: 'oklch(0.84 0.01 258)',
                    ring: 'oklch(0.58 0.15 230)',
                    sidebarRing: 'oklch(0.58 0.15 230)',
                }),
                radius: {
                    sm: '0.2rem',
                    md: '0.35rem',
                    lg: '0.55rem',
                    xl: '0.9rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"IBM Plex Sans", "Inter", sans-serif',
                    familyMono: '"JetBrains Mono", "Fira Code", monospace',
                    sizeSm: '0.75rem',
                    sizeMd: '0.875rem',
                    sizeLg: '1rem',
                    weightNormal: '410',
                    weightMedium: '560',
                    weightBold: '680',
                    lineHeight: '1.5',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-01',
                    panelOverlayOpacity: '0.22',
                    glassBlur: '10px',
                },
            }),
            dark: createThemeDefinition('graphite-dark', 'dark', defaultDarkTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.17 0.01 250)',
                    foreground: 'oklch(0.9 0.015 250)',
                    card: 'oklch(0.2 0.012 250)',
                    cardForeground: 'oklch(0.93 0.02 250)',
                    popover: 'oklch(0.23 0.014 250)',
                    popoverForeground: 'oklch(0.94 0.02 250)',
                    border: 'oklch(0.33 0.01 250)',
                    primary: 'oklch(0.74 0.14 225)',
                    primaryForeground: 'oklch(0.2 0.02 230)',
                    secondary: 'oklch(0.24 0.012 250)',
                    secondaryForeground: 'oklch(0.92 0.02 250)',
                    muted: 'oklch(0.22 0.01 250)',
                    mutedForeground: 'oklch(0.7 0.02 250)',
                    accent: 'oklch(0.28 0.016 248)',
                    accentForeground: 'oklch(0.93 0.02 250)',
                    destructive: 'oklch(0.66 0.2 28)',
                    destructiveForeground: 'oklch(0.2 0.02 28)',
                    input: 'oklch(0.29 0.012 250)',
                    ring: 'oklch(0.74 0.14 225)',
                    sidebar: 'oklch(0.14 0.008 248)',
                    sidebarForeground: 'oklch(0.89 0.015 250)',
                    sidebarAccent: 'oklch(0.21 0.012 248)',
                    sidebarAccentForeground: 'oklch(0.92 0.02 250)',
                    sidebarBorder: 'oklch(0.28 0.01 248)',
                    sidebarRing: 'oklch(0.74 0.14 225)',
                }),
                radius: {
                    sm: '0.2rem',
                    md: '0.35rem',
                    lg: '0.55rem',
                    xl: '0.9rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"IBM Plex Sans", "Inter", sans-serif',
                    familyMono: '"JetBrains Mono", "Fira Code", monospace',
                    sizeSm: '0.75rem',
                    sizeMd: '0.875rem',
                    sizeLg: '1rem',
                    weightNormal: '410',
                    weightMedium: '560',
                    weightBold: '680',
                    lineHeight: '1.5',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-02',
                    panelOverlayOpacity: '0.28',
                    glassBlur: '12px',
                },
            }),
        },
    },
    sunset: {
        id: 'sunset',
        label: 'Sunset',
        description: 'Warm rounded reskin with stronger depth and motion contrast.',
        extends: 'classic',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['warm', 'reskin'],
        themes: {
            light: createThemeDefinition('sunset-light', 'light', defaultLightTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.97 0.03 75)',
                    foreground: 'oklch(0.34 0.06 42)',
                    card: 'oklch(0.99 0.02 88)',
                    cardForeground: 'oklch(0.36 0.06 44)',
                    border: 'oklch(0.86 0.06 70)',
                    primary: 'oklch(0.69 0.2 34)',
                    primaryForeground: 'oklch(0.98 0.01 85)',
                    secondary: 'oklch(0.95 0.03 80)',
                    secondaryForeground: 'oklch(0.38 0.06 44)',
                    muted: 'oklch(0.92 0.03 70)',
                    mutedForeground: 'oklch(0.5 0.08 40)',
                    accent: 'oklch(0.95 0.05 82)',
                    accentForeground: 'oklch(0.34 0.06 42)',
                    destructive: 'oklch(0.62 0.24 26)',
                    destructiveForeground: 'oklch(0.98 0.01 26)',
                    sidebar: 'oklch(0.955 0.025 78)',
                    sidebarForeground: 'oklch(0.34 0.06 42)',
                    sidebarAccent: 'oklch(0.92 0.05 66)',
                    sidebarAccentForeground: 'oklch(0.34 0.06 42)',
                    sidebarBorder: 'oklch(0.84 0.06 66)',
                    ring: 'oklch(0.69 0.2 34)',
                    sidebarRing: 'oklch(0.69 0.2 34)',
                }),
                radius: {
                    sm: '0.35rem',
                    md: '0.65rem',
                    lg: '1rem',
                    xl: '1.4rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Sora", "Avenir Next", sans-serif',
                    familyMono: '"IBM Plex Mono", monospace',
                    sizeSm: '0.76rem',
                    sizeMd: '0.92rem',
                    sizeLg: '1.08rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.45',
                },
                elevation: {
                    level1: '0 3px 12px oklch(0.55 0.07 45 / 0.14)',
                    level2: '0 8px 24px oklch(0.45 0.09 35 / 0.18)',
                    level3: '0 14px 42px oklch(0.4 0.11 30 / 0.24)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/mesh-01',
                    panelOverlayOpacity: '0.2',
                    glassBlur: '6px',
                },
            }),
            dark: createThemeDefinition('sunset-dark', 'dark', defaultDarkTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.2 0.03 18)',
                    foreground: 'oklch(0.92 0.03 80)',
                    card: 'oklch(0.24 0.03 20)',
                    cardForeground: 'oklch(0.93 0.03 78)',
                    popover: 'oklch(0.27 0.03 22)',
                    popoverForeground: 'oklch(0.94 0.03 80)',
                    border: 'oklch(0.38 0.04 26)',
                    primary: 'oklch(0.75 0.2 42)',
                    primaryForeground: 'oklch(0.24 0.03 22)',
                    secondary: 'oklch(0.3 0.03 24)',
                    secondaryForeground: 'oklch(0.93 0.03 78)',
                    muted: 'oklch(0.28 0.03 22)',
                    mutedForeground: 'oklch(0.72 0.04 66)',
                    accent: 'oklch(0.34 0.05 28)',
                    accentForeground: 'oklch(0.93 0.03 78)',
                    destructive: 'oklch(0.68 0.22 28)',
                    destructiveForeground: 'oklch(0.24 0.03 26)',
                    input: 'oklch(0.34 0.04 25)',
                    sidebar: 'oklch(0.17 0.028 18)',
                    sidebarForeground: 'oklch(0.9 0.03 78)',
                    sidebarAccent: 'oklch(0.25 0.04 22)',
                    sidebarAccentForeground: 'oklch(0.92 0.03 78)',
                    sidebarBorder: 'oklch(0.32 0.04 24)',
                    ring: 'oklch(0.75 0.2 42)',
                    sidebarRing: 'oklch(0.75 0.2 42)',
                }),
                radius: {
                    sm: '0.35rem',
                    md: '0.65rem',
                    lg: '1rem',
                    xl: '1.4rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Sora", "Avenir Next", sans-serif',
                    familyMono: '"IBM Plex Mono", monospace',
                    sizeSm: '0.76rem',
                    sizeMd: '0.92rem',
                    sizeLg: '1.08rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.45',
                },
                elevation: {
                    level1: '0 2px 8px oklch(0.1 0.02 24 / 0.4)',
                    level2: '0 8px 22px oklch(0.08 0.02 22 / 0.5)',
                    level3: '0 14px 36px oklch(0.06 0.02 20 / 0.56)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-03',
                    panelOverlayOpacity: '0.34',
                    glassBlur: '12px',
                },
            }),
        },
    },
    forge: {
        id: 'forge',
        label: 'Forge',
        description: 'Steel-blue operator skin tuned for dense multi-panel work.',
        extends: 'graphite',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['forge', 'operator', 'dense'],
        themes: {
            light: createThemeDefinition('forge-light', 'light', defaultLightTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.97 0.008 240)',
                    foreground: 'oklch(0.24 0.03 248)',
                    card: 'oklch(0.995 0.004 245)',
                    cardForeground: 'oklch(0.24 0.03 248)',
                    popover: 'oklch(1 0.004 245)',
                    popoverForeground: 'oklch(0.24 0.03 248)',
                    border: 'oklch(0.86 0.012 245)',
                    primary: 'oklch(0.57 0.16 235)',
                    primaryForeground: 'oklch(0.985 0.01 245)',
                    secondary: 'oklch(0.945 0.008 245)',
                    secondaryForeground: 'oklch(0.26 0.03 245)',
                    muted: 'oklch(0.93 0.008 245)',
                    mutedForeground: 'oklch(0.47 0.025 245)',
                    accent: 'oklch(0.915 0.014 242)',
                    accentForeground: 'oklch(0.24 0.03 248)',
                    destructive: 'oklch(0.63 0.19 30)',
                    destructiveForeground: 'oklch(0.99 0.01 30)',
                    sidebar: 'oklch(0.94 0.01 243)',
                    sidebarForeground: 'oklch(0.23 0.03 246)',
                    sidebarAccent: 'oklch(0.885 0.02 238)',
                    sidebarAccentForeground: 'oklch(0.23 0.03 246)',
                    sidebarBorder: 'oklch(0.84 0.012 243)',
                    ring: 'oklch(0.57 0.16 235)',
                    sidebarRing: 'oklch(0.57 0.16 235)',
                }),
                typography: {
                    familySans: '"Aptos", "IBM Plex Sans", sans-serif',
                    familyMono: '"JetBrains Mono", "Cascadia Code", monospace',
                    sizeSm: '0.78rem',
                    sizeMd: '0.9rem',
                    sizeLg: '1.04rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.48',
                },
                elevation: {
                    level1: '0 8px 18px oklch(0.58 0.03 245 / 0.14)',
                    level2: '0 16px 32px oklch(0.52 0.04 245 / 0.2)',
                    level3: '0 24px 56px oklch(0.48 0.05 245 / 0.28)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/mesh-01',
                    panelOverlayOpacity: '0.16',
                    glassBlur: '18px',
                },
            }),
            dark: createThemeDefinition('forge-dark', 'dark', defaultDarkTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.15 0.012 245)',
                    foreground: 'oklch(0.93 0.015 250)',
                    card: 'oklch(0.185 0.013 245)',
                    cardForeground: 'oklch(0.94 0.015 250)',
                    popover: 'oklch(0.21 0.015 245)',
                    popoverForeground: 'oklch(0.95 0.015 250)',
                    border: 'oklch(0.32 0.015 245)',
                    primary: 'oklch(0.72 0.15 235)',
                    primaryForeground: 'oklch(0.18 0.015 245)',
                    secondary: 'oklch(0.21 0.012 245)',
                    secondaryForeground: 'oklch(0.92 0.015 250)',
                    muted: 'oklch(0.19 0.012 245)',
                    mutedForeground: 'oklch(0.73 0.02 245)',
                    accent: 'oklch(0.28 0.025 238)',
                    accentForeground: 'oklch(0.93 0.015 250)',
                    destructive: 'oklch(0.67 0.19 30)',
                    destructiveForeground: 'oklch(0.18 0.015 245)',
                    input: 'oklch(0.28 0.014 245)',
                    sidebar: 'oklch(0.12 0.014 245)',
                    sidebarForeground: 'oklch(0.9 0.016 250)',
                    sidebarAccent: 'oklch(0.18 0.018 240)',
                    sidebarAccentForeground: 'oklch(0.93 0.015 250)',
                    sidebarBorder: 'oklch(0.24 0.015 245)',
                    ring: 'oklch(0.72 0.15 235)',
                    sidebarRing: 'oklch(0.72 0.15 235)',
                }),
                typography: {
                    familySans: '"Aptos", "IBM Plex Sans", sans-serif',
                    familyMono: '"JetBrains Mono", "Cascadia Code", monospace',
                    sizeSm: '0.78rem',
                    sizeMd: '0.9rem',
                    sizeLg: '1.04rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.48',
                },
                elevation: {
                    level1: '0 10px 24px oklch(0.02 0.01 245 / 0.35)',
                    level2: '0 20px 44px oklch(0.02 0.01 245 / 0.44)',
                    level3: '0 28px 68px oklch(0.02 0.01 245 / 0.56)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-03',
                    panelOverlayOpacity: '0.22',
                    glassBlur: '18px',
                },
            }),
        },
        iconAliases: {
            search: 'wrench',
            menu: 'settings2',
        },
        metadata: {
            accentIntent: 'operator',
        },
    },
    atelier: {
        id: 'atelier',
        label: 'Atelier',
        description: 'Pearlescent editorial skin with softer contrast and richer atmosphere.',
        extends: 'classic',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['editorial', 'glamour', 'demo'],
        themes: {
            light: createThemeDefinition('atelier-light', 'light', defaultLightTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.978 0.012 82)',
                    foreground: 'oklch(0.27 0.028 255)',
                    card: 'oklch(0.995 0.006 92)',
                    cardForeground: 'oklch(0.27 0.028 255)',
                    popover: 'oklch(1 0.006 92)',
                    popoverForeground: 'oklch(0.27 0.028 255)',
                    border: 'oklch(0.88 0.02 88)',
                    primary: 'oklch(0.73 0.16 28)',
                    primaryForeground: 'oklch(0.985 0.008 92)',
                    secondary: 'oklch(0.965 0.014 88)',
                    secondaryForeground: 'oklch(0.29 0.028 255)',
                    muted: 'oklch(0.94 0.015 84)',
                    mutedForeground: 'oklch(0.46 0.03 255)',
                    accent: 'oklch(0.955 0.02 88)',
                    accentForeground: 'oklch(0.27 0.028 255)',
                    destructive: 'oklch(0.65 0.19 24)',
                    destructiveForeground: 'oklch(0.99 0.01 24)',
                    input: 'oklch(0.89 0.018 90)',
                    sidebar: 'oklch(0.965 0.012 84)',
                    sidebarForeground: 'oklch(0.3 0.03 255)',
                    sidebarAccent: 'oklch(0.94 0.024 84)',
                    sidebarAccentForeground: 'oklch(0.28 0.028 255)',
                    sidebarBorder: 'oklch(0.86 0.02 84)',
                    ring: 'oklch(0.73 0.16 28)',
                    sidebarRing: 'oklch(0.73 0.16 28)',
                }),
                radius: {
                    sm: '0.45rem',
                    md: '0.8rem',
                    lg: '1.25rem',
                    xl: '1.75rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Space Grotesk", "Aptos", sans-serif',
                    familyMono: '"IBM Plex Mono", "JetBrains Mono", monospace',
                    sizeSm: '0.79rem',
                    sizeMd: '0.95rem',
                    sizeLg: '1.12rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.5',
                },
                elevation: {
                    level1: '0 8px 22px oklch(0.72 0.05 70 / 0.12)',
                    level2: '0 18px 44px oklch(0.56 0.05 38 / 0.18)',
                    level3: '0 28px 70px oklch(0.45 0.04 28 / 0.24)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/mesh-01',
                    panelOverlayOpacity: '0.1',
                    glassBlur: '22px',
                },
            }),
            dark: createThemeDefinition('atelier-dark', 'dark', defaultDarkTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.2 0.018 252)',
                    foreground: 'oklch(0.94 0.018 90)',
                    card: 'oklch(0.235 0.018 250)',
                    cardForeground: 'oklch(0.95 0.018 90)',
                    popover: 'oklch(0.255 0.018 248)',
                    popoverForeground: 'oklch(0.95 0.018 90)',
                    border: 'oklch(0.35 0.02 248)',
                    primary: 'oklch(0.78 0.14 30)',
                    primaryForeground: 'oklch(0.22 0.018 252)',
                    secondary: 'oklch(0.29 0.018 248)',
                    secondaryForeground: 'oklch(0.94 0.018 90)',
                    muted: 'oklch(0.27 0.018 248)',
                    mutedForeground: 'oklch(0.76 0.025 92)',
                    accent: 'oklch(0.33 0.03 244)',
                    accentForeground: 'oklch(0.95 0.018 90)',
                    destructive: 'oklch(0.69 0.2 24)',
                    destructiveForeground: 'oklch(0.21 0.018 252)',
                    input: 'oklch(0.31 0.02 248)',
                    sidebar: 'oklch(0.16 0.018 248)',
                    sidebarForeground: 'oklch(0.92 0.018 90)',
                    sidebarAccent: 'oklch(0.24 0.022 244)',
                    sidebarAccentForeground: 'oklch(0.94 0.018 90)',
                    sidebarBorder: 'oklch(0.28 0.02 246)',
                    ring: 'oklch(0.78 0.14 30)',
                    sidebarRing: 'oklch(0.78 0.14 30)',
                }),
                radius: {
                    sm: '0.45rem',
                    md: '0.8rem',
                    lg: '1.25rem',
                    xl: '1.75rem',
                    pill: '999px',
                },
                typography: {
                    familySans: '"Space Grotesk", "Aptos", sans-serif',
                    familyMono: '"IBM Plex Mono", "JetBrains Mono", monospace',
                    sizeSm: '0.79rem',
                    sizeMd: '0.95rem',
                    sizeLg: '1.12rem',
                    weightNormal: '430',
                    weightMedium: '600',
                    weightBold: '720',
                    lineHeight: '1.5',
                },
                elevation: {
                    level1: '0 10px 24px oklch(0.04 0.01 250 / 0.32)',
                    level2: '0 22px 48px oklch(0.04 0.01 250 / 0.42)',
                    level3: '0 34px 82px oklch(0.04 0.01 250 / 0.52)',
                },
                fx: {
                    panelTexture: 'asset://texture/panel/noise-02',
                    panelOverlayOpacity: '0.16',
                    glassBlur: '24px',
                },
            }),
        },
        metadata: {
            accentIntent: 'editorial',
            preferredUiExtensionIds: ['atelier-panel-surface'],
        },
    },
    command: {
        id: 'command',
        label: 'Command',
        description: 'High-hierarchy dark ops skin tuned for dense queues, tables, and sidebars.',
        extends: 'forge',
        source: '@loop-kit/ui/skins/defaultUiSkinDefinitions',
        tags: ['operator', 'high-contrast', 'dense'],
        themes: {
            light: createThemeDefinition('command-light', 'light', defaultLightTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.968 0.01 230)',
                    foreground: 'oklch(0.2 0.02 245)',
                    card: 'oklch(0.992 0.004 232)',
                    cardForeground: 'oklch(0.2 0.02 245)',
                    border: 'oklch(0.84 0.01 235)',
                    primary: 'oklch(0.59 0.13 220)',
                    primaryForeground: 'oklch(0.985 0.01 235)',
                    secondary: 'oklch(0.94 0.01 235)',
                    secondaryForeground: 'oklch(0.24 0.02 245)',
                    muted: 'oklch(0.93 0.008 235)',
                    mutedForeground: 'oklch(0.44 0.02 245)',
                    accent: 'oklch(0.9 0.012 228)',
                    accentForeground: 'oklch(0.22 0.02 245)',
                    destructive: 'oklch(0.63 0.19 30)',
                    destructiveForeground: 'oklch(0.99 0.01 30)',
                    sidebar: 'oklch(0.925 0.012 235)',
                    sidebarForeground: 'oklch(0.22 0.02 245)',
                    sidebarAccent: 'oklch(0.87 0.016 228)',
                    sidebarAccentForeground: 'oklch(0.22 0.02 245)',
                    sidebarBorder: 'oklch(0.8 0.012 235)',
                    ring: 'oklch(0.59 0.13 220)',
                    sidebarRing: 'oklch(0.59 0.13 220)',
                }),
            }),
            dark: createThemeDefinition('command-dark', 'dark', defaultDarkTheme, {
                colors: createSemanticColors({
                    background: 'oklch(0.125 0.012 245)',
                    foreground: 'oklch(0.93 0.014 245)',
                    card: 'oklch(0.17 0.013 245)',
                    cardForeground: 'oklch(0.94 0.014 245)',
                    popover: 'oklch(0.19 0.014 245)',
                    popoverForeground: 'oklch(0.95 0.014 245)',
                    border: 'oklch(0.27 0.012 245)',
                    primary: 'oklch(0.72 0.13 220)',
                    primaryForeground: 'oklch(0.16 0.012 245)',
                    secondary: 'oklch(0.2 0.012 245)',
                    secondaryForeground: 'oklch(0.92 0.014 245)',
                    muted: 'oklch(0.18 0.012 245)',
                    mutedForeground: 'oklch(0.72 0.018 245)',
                    accent: 'oklch(0.24 0.018 232)',
                    accentForeground: 'oklch(0.94 0.014 245)',
                    destructive: 'oklch(0.67 0.19 30)',
                    destructiveForeground: 'oklch(0.16 0.012 245)',
                    input: 'oklch(0.24 0.012 245)',
                    sidebar: 'oklch(0.1 0.01 245)',
                    sidebarForeground: 'oklch(0.89 0.014 245)',
                    sidebarAccent: 'oklch(0.16 0.014 235)',
                    sidebarAccentForeground: 'oklch(0.93 0.014 245)',
                    sidebarBorder: 'oklch(0.2 0.012 245)',
                    ring: 'oklch(0.72 0.13 220)',
                    sidebarRing: 'oklch(0.72 0.13 220)',
                }),
                fx: {
                    panelTexture: 'asset://texture/panel/noise-03',
                    panelOverlayOpacity: '0.28',
                    glassBlur: '14px',
                },
            }),
        },
        metadata: {
            accentIntent: 'control-room',
        },
    },
};

export const defaultUiSkinRegistry = createUiSkinRegistry({
    skins: defaultUiSkinDefinitions,
});

export const defaultUiSkins = defaultUiSkinRegistry.resolved();

export const defaultUiSkin = defaultUiSkins[DEFAULT_UI_SKIN_ID]!;

export function resolveDefaultUiSkin(id: string = DEFAULT_UI_SKIN_ID): ResolvedUiSkin {
    return defaultUiSkins[id] ?? defaultUiSkin;
}
