export default function App() {
  return (
    <main style={{ fontFamily: 'ui-sans-serif, system-ui', padding: 24 }}>
      <h1>__TITLE__</h1>
      <p>Generated by loop new app.</p>
    </main>
  );
}
