import path from 'node:path';
import {
    err,
    ok,
    type ComponentManifest,
    type PatchOperation,
    type Result,
} from '@loop-kit/loop-contracts';
import { nodeFsGateway, type FsGateway } from '../io/fsGateway.js';
import { executePatchPlan } from '../patch/executor.js';
import {
    captureFileStates,
    collectPatchPlanTouchedFiles,
} from '../undo/snapshot.js';
import type { AdoptResult } from '../types.js';
import { readComponentLockfile } from './lockfile.js';
import { stableStringify } from '../utils/json.js';

function sanitizeComponentId(componentId: string): string {
    return componentId.trim().replace(/[^a-zA-Z0-9._/-]/g, '-');
}

function findInstalledRecord(
    installs: Awaited<ReturnType<typeof readComponentLockfile>>['installs'],
    installedRef: string,
) {
    return installs.find((record) => record.ref === installedRef)
        ?? installs.find((record) => record.componentId === installedRef)
        ?? installs.find((record) => `${record.componentId}@${record.snapshotId}` === installedRef);
}

export async function adoptComponent(
    workspaceRoot: string,
    installedRef: string,
    asComponentId: string,
    options: {
        dryRun?: boolean;
        fs?: FsGateway;
    } = {},
): Promise<Result<AdoptResult>> {
    const fs = options.fs ?? nodeFsGateway;
    const lockfile = await readComponentLockfile(workspaceRoot, fs);
    const installed = findInstalledRecord(lockfile.installs, installedRef);
    if (!installed) {
        return err({
            code: 'component.adopt_not_found',
            message: `Installed component not found for ref: ${installedRef}`,
        });
    }

    const normalizedId = sanitizeComponentId(asComponentId);
    if (!normalizedId) {
        return err({
            code: 'component.adopt_invalid_id',
            message: `Invalid component ID: ${asComponentId}`,
        });
    }

    const componentDir = path.join('loop', 'components', normalizedId);
    const filesDir = path.join(componentDir, 'files');
    const operations: PatchOperation[] = [];
    const manifestFiles: ComponentManifest['files'] = [];

    for (const managedFile of installed.managedFiles) {
        const absoluteManagedPath = path.resolve(workspaceRoot, managedFile.path);
        if (!(await fs.exists(absoluteManagedPath))) {
            continue;
        }

        const targetRelative = path
            .relative(installed.targetPath, managedFile.path)
            .replace(/\\/g, '/');
        if (targetRelative.startsWith('../')) {
            continue;
        }

        const sourceRelative = `files/${targetRelative}`;
        const outputPath = path.join(filesDir, targetRelative);
        const content = await fs.readText(absoluteManagedPath);
        operations.push({
            kind: 'ensureFile',
            opId: `component.adopt.file.${targetRelative}`,
            path: outputPath,
            overwrite: true,
            content,
        });
        manifestFiles.push({
            source: sourceRelative,
            target: targetRelative,
        });
    }

    const manifest: ComponentManifest = {
        schemaVersion: '1',
        kind: 'component',
        id: normalizedId,
        name: normalizedId,
        version: '0.1.0',
        description: `Adopted from installed ref ${installed.ref}`,
        snapshot: installed.snapshotId,
        files: manifestFiles,
        patches: [],
        dependencies: [],
        targets: ['app', 'pkg'],
        metadata: {
            upstream: {
                ref: installed.ref,
                componentId: installed.componentId,
                snapshotId: installed.snapshotId,
                laneId: installed.laneId,
                adoptedAt: new Date().toISOString(),
            },
        },
    };

    operations.push({
        kind: 'ensureFile',
        opId: 'component.adopt.manifest',
        path: path.join(componentDir, 'loop.component.json'),
        overwrite: true,
        content: stableStringify(manifest),
    });

    const previewPath = path.join(componentDir, 'preview.tsx');
    operations.push({
        kind: 'ensureFile',
        opId: 'component.adopt.preview',
        path: previewPath,
        overwrite: false,
        content: [
            'import React from \'react\';',
            '',
            `export default function ${normalizedId.replace(/[^a-zA-Z0-9]/g, '_')}Preview() {`,
            '    return (',
            '        <div style={{ padding: 16 }}>',
            `            <h3>${normalizedId}</h3>`,
            '            <p>Preview stub generated by loop adopt.</p>',
            '        </div>',
            '    );',
            '}',
            '',
        ].join('\n'),
    });

    const plan = {
        id: `component.adopt.${normalizedId}`,
        title: `Adopt ${installed.ref} as ${normalizedId}`,
        provenance: {
            source: 'loop:adopt',
            componentId: normalizedId,
            snapshotId: installed.snapshotId,
        },
        operations,
        preconditions: [],
        postconditions: [],
    };

    const touchedFiles = collectPatchPlanTouchedFiles(plan);
    const before = await captureFileStates(workspaceRoot, touchedFiles, fs);
    const execution = await executePatchPlan(plan, {
        workspaceRoot,
        dryRun: options.dryRun,
        fs,
    });
    const after = execution.applied
        ? await captureFileStates(workspaceRoot, touchedFiles, fs)
        : before;

    return ok({
        componentId: normalizedId,
        sourceInstallRef: installed.ref,
        sourcePath: installed.targetPath,
        componentDir,
        previewPath,
        manifest,
        plan,
        execution,
        undoSnapshot: {
            touchedFiles,
            before,
            after,
        },
    });
}
