package loop:host;

interface input {
    enum key {
        a, b, c, d, e, f, g, h, i, j, k, l, m,
        n, o, p, q, r, s, t, u, v, w, x, y, z,
        escape,
        space,
        enter,
        up, down, left, right,
    }

    is-key-pressed: func(key: key) -> bool;
    is-key-down: func(key: key) -> bool;

    get-mouse-position: func() -> tuple<f64, f64>;
    is-mouse-button-down: func(button: u32) -> bool;
}