package loop:host;

interface window {
    create: func(title: string, width: u32, height: u32);
    show: func();
    close: func();
    clear: func(r: f32, g: f32, b: f32, a: f32);

    get-size: func() -> tuple<u32, u32>;
    set-size: func(width: u32, height: u32);
    set-title: func(title: string);
}