package loop:host;

interface log {
    info: func(msg: string);
    warn: func(msg: string);
    error: func(msg: string);
}

interface graphics {
    draw-rect: func(x: f32, y: f32, width: f32, height: f32, r: f32, g: f32, b: f32, a: f32);
    draw-circle: func(x: f32, y: f32, radius: f32, r: f32, g: f32, b: f32, a: f32);
}

world loop-host {
    import window;
    import input;
    import graphics;
    import log;
}