$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  build:
    command: 'pnpm'
    args:
      - 'run'
      - '--if-present'
      - 'build'
    toolchains:
      - 'node'
      - 'pnpm'
    options:
      runInCI: true

  typecheck:
    command: 'pnpm'
    args:
      - 'run'
      - '--if-present'
      - 'typecheck'
    toolchains:
      - 'node'
      - 'pnpm'
    options:
      runInCI: true

  test:
    command: 'pnpm'
    args:
      - 'run'
      - '--if-present'
      - 'test'
    toolchains:
      - 'node'
      - 'pnpm'
    options:
      runInCI: true

  lint:
    command: 'pnpm'
    args:
      - 'run'
      - '--if-present'
      - 'lint'
    toolchains:
      - 'node'
      - 'pnpm'
    options:
      runInCI: true
