// examples/hello-window/wit/world.wit
package hello:window@0.1.0;

world app {
    include wasi:surface/imports@0.0.1;
    include wasi:graphics-context/imports@0.0.1;
    include wasi:frame-buffer/imports@0.0.1;

    export start: func();
    import print: func(s: string);
}